services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - 'db'

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: AdminPassword
      POSTGRES_DB: api_database
